apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mock-psp-dev

images:
  - name: mock-psp-image
    newName: nodopasitregistry.azurecr.io/mock-psp
    newTag: 0.0.1

resources:
  - namespace.yaml
  - ingress.yaml
  - ../base

generatorOptions:
  disableNameSuffixHash: true
